/* =============================================================================
   Systock - Case Tecnico de Integracao de Dados
   Arquivo 01 - DDL CORRIGIDO

   Este e o script que cria a estrutura do banco. Cada correcao em relacao ao
   DDL do enunciado esta marcada com [CORRECAO] e o codigo do problema
   catalogado em docs/02_catalogo_inconsistencias.md.

   Execucao:
       psql -U postgres -d systock -f sql/01_ddl_corrigido.sql

   Ordem de criacao respeita as dependencias de FK:
       fornecedor -> produtos_filial -> pedido_compra -> entradas_mercadoria
       venda (independente)
   ============================================================================= */

-- Schemas -------------------------------------------------------------------
-- public : modelo de negocio (tabelas finais)
-- stg    : staging de carga, tudo TEXT (criado em 02_staging_e_carga.sql)
-- qa     : views de qualidade de dados (criado em 99_qualidade_dados.sql)
CREATE SCHEMA IF NOT EXISTS stg;
CREATE SCHEMA IF NOT EXISTS qa;

DROP TABLE IF EXISTS public.entradas_mercadoria CASCADE;
DROP TABLE IF EXISTS public.pedido_compra       CASCADE;
DROP TABLE IF EXISTS public.produtos_filial     CASCADE;
DROP TABLE IF EXISTS public.fornecedor          CASCADE;
DROP TABLE IF EXISTS public.venda               CASCADE;


-- =============================================================================
-- 1. FORNECEDOR
-- =============================================================================
CREATE TABLE public.fornecedor (
    -- [CORRECAO E-10] "idforncedor" -> "idfornecedor" (grafia da planilha).
    idfornecedor    varchar(25)  NOT NULL,

    -- [CORRECAO E-02] Chave substituta NUMERICA.
    -- A planilha traz a chave natural como texto ('F1'..'F20'), mas
    -- pedido_compra.fornecedor_id e numerico (1..20). Sem um identificador
    -- numerico em fornecedor, as duas tabelas nao se relacionam.
    -- Esta coluna e tambem o alvo da trigger da Parte 3 (item 4).
    fornecedor_num  int  GENERATED BY DEFAULT AS IDENTITY,

    razao_social    varchar(255) NOT NULL,
    criado_em       timestamptz  NOT NULL DEFAULT now(),

    -- [CORRECAO E-11] PK era (idforncedor, idproduto). A coluna idproduto nao
    -- existe nesta tabela e sua presenca na PK quebraria a 2FN.
    CONSTRAINT fornecedor_pkey      PRIMARY KEY (idfornecedor),
    CONSTRAINT fornecedor_num_uk    UNIQUE (fornecedor_num),
    CONSTRAINT fornecedor_razao_ck  CHECK (length(trim(razao_social)) > 0)
);

COMMENT ON TABLE  public.fornecedor IS
    'Cadastro de fornecedores. Chave natural textual (idfornecedor) + chave substituta numerica (fornecedor_num) para relacionamento com pedido_compra.';
COMMENT ON COLUMN public.fornecedor.fornecedor_num IS
    'Chave numerica. Criada para viabilizar o relacionamento com pedido_compra.fornecedor_id (int) e alimentada pela trigger da Parte 3.';


-- =============================================================================
-- 2. PRODUTOS_FILIAL
-- =============================================================================
CREATE TABLE public.produtos_filial (
    -- [CORRECAO M-12] Coluna de PK nao pode ser NULL.
    filial_id           int          NOT NULL,

    -- [CORRECAO E-04/E-09] Nome alinhado com a planilha (idproduto) e com a PK,
    -- que ja referenciava "idproduto" enquanto a coluna se chamava "produto_id".
    -- [CORRECAO M-02] varchar(25), o mesmo dominio usado nas demais tabelas.
    idproduto           varchar(25)  NOT NULL,

    -- [CORRECAO E-05] "decricao" -> "descricao".
    descricao           varchar(255) NOT NULL,

    -- [CORRECAO M-03] float8 -> numeric em quantidade e valores monetarios.
    estoque             numeric(14,3) NOT NULL DEFAULT 0,
    preco_unitario      numeric(12,4) NOT NULL DEFAULT 0,
    preco_compra        numeric(12,4) NOT NULL DEFAULT 0,
    preco_venda         numeric(12,4) NOT NULL DEFAULT 0,

    -- [CORRECAO E-06] "idfonecedor" -> "idfornecedor".
    -- [CORRECAO E-08] int4 -> varchar(25): a planilha traz 'F8', 'F9', 'F10'.
    idfornecedor        varchar(25)  NULL,

    -- Parte 3, item 4: preenchida automaticamente pela trigger
    -- (ver sql/05_parte3_trigger_fornecedor.sql).
    idfornecedor_num    int          NULL,

    -- [CORRECAO E-07] Faltava a virgula antes do CONSTRAINT no DDL original.
    CONSTRAINT produtos_filial_pkey PRIMARY KEY (filial_id, idproduto),

    -- [CORRECAO F-01] FK ausente no original.
    CONSTRAINT produtos_filial_fornecedor_fk
        FOREIGN KEY (idfornecedor) REFERENCES public.fornecedor (idfornecedor)
        ON UPDATE CASCADE ON DELETE SET NULL,

    -- [CORRECAO F-02] CHECKs ausentes no original.
    CONSTRAINT produtos_filial_estoque_ck  CHECK (estoque        >= 0),
    CONSTRAINT produtos_filial_pcompra_ck  CHECK (preco_compra   >= 0),
    CONSTRAINT produtos_filial_pvenda_ck   CHECK (preco_venda    >= 0),
    CONSTRAINT produtos_filial_punit_ck    CHECK (preco_unitario >= 0)
);

COMMENT ON TABLE public.produtos_filial IS
    'Cadastro de produtos por filial. ATENCAO: possui tres colunas de preco (unitario, compra, venda) sem definicao de qual e a oficial - pendencia de validacao com o cliente.';

-- Observacao deliberada: NAO foi criado CHECK (preco_venda >= preco_compra).
-- A base tem 4 produtos com margem negativa (P1, P8, P15, P18). Bloquear a
-- carga esconderia o problema; o correto e carregar, sinalizar em qa e levar
-- para a reuniao de validacao. Ver docs/03.


-- =============================================================================
-- 3. PEDIDO_COMPRA
-- =============================================================================
CREATE TABLE public.pedido_compra (
    -- [CORRECAO M-08] float8 -> bigint/int em identificadores.
    -- Ponto flutuante nao garante igualdade exata: e tipo impróprio para chave.
    pedido_id           bigint        NOT NULL,
    item                int           NOT NULL DEFAULT 1,
    ordem_compra        bigint        NOT NULL DEFAULT 0,

    data_pedido         date          NULL,

    -- [CORRECAO M-09] DEFAULT '0' removido: uma carga incompleta deve falhar,
    -- nao entrar com produto fantasma.
    produto_id          varchar(25)   NOT NULL,
    descricao_produto   varchar(255)  NULL,

    qtde_pedida         numeric(14,3) NULL,
    filial_id           int           NULL,
    data_entrega        date          NULL,
    qtde_entregue       numeric(14,3) NOT NULL DEFAULT 0,

    -- [CORRECAO D-01] A coluna existe no DDL do enunciado mas NAO na planilha.
    -- Decisao: manter no modelo e derivar na carga como
    -- GREATEST(qtde_pedida - qtde_entregue, 0). Ver docs/01.
    qtde_pendente       numeric(14,3) NOT NULL DEFAULT 0,

    -- [CORRECAO M-11] float8 -> numeric(12,4), alinhado com venda.valor_unitario.
    preco_compra        numeric(12,4) NULL DEFAULT 0,

    fornecedor_id       int           NULL,

    CONSTRAINT pedido_compra_pkey PRIMARY KEY (pedido_id, produto_id, item),

    -- [CORRECAO E-02/F-01] Relacionamento viabilizado pela chave numerica
    -- criada em fornecedor.
    CONSTRAINT pedido_compra_fornecedor_fk
        FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedor (fornecedor_num)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT pedido_compra_qtde_ck    CHECK (qtde_pedida   IS NULL OR qtde_pedida >= 0),
    CONSTRAINT pedido_compra_entreg_ck  CHECK (qtde_entregue >= 0),
    CONSTRAINT pedido_compra_preco_ck   CHECK (preco_compra  IS NULL OR preco_compra >= 0)
);

COMMENT ON COLUMN public.pedido_compra.ordem_compra IS
    'Chave de ligacao com entradas_mercadoria. ATENCAO: 11 registros da base chegam com valor 0 (orfaos) - ver qa.vw_pedido_sem_ordem_compra.';
COMMENT ON COLUMN public.pedido_compra.qtde_pendente IS
    'Coluna ausente na planilha de origem. Derivada na carga: GREATEST(qtde_pedida - qtde_entregue, 0).';

-- Observacao deliberada: NAO foi criado CHECK (data_entrega >= data_pedido).
-- A base tem 20 registros com entrega anterior ao pedido. Mesma logica dos
-- precos: sinalizar em qa, nao bloquear.

CREATE INDEX ix_pedido_compra_ordem    ON public.pedido_compra (ordem_compra);
CREATE INDEX ix_pedido_compra_produto  ON public.pedido_compra (produto_id);
CREATE INDEX ix_pedido_compra_data     ON public.pedido_compra (data_pedido);


-- =============================================================================
-- 4. ENTRADAS_MERCADORIA
-- =============================================================================
CREATE TABLE public.entradas_mercadoria (
    -- [CORRECAO E-03] *** A coluna que faltava por completo no DDL original. ***
    -- Sem ela o CREATE TABLE do enunciado nao executa, e e justamente o campo
    -- que o proprio enunciado indica como ligacao com pedido_compra.
    ordem_compra        bigint        NOT NULL,

    nro_nfe             varchar(255)  NOT NULL,
    item                int           NOT NULL DEFAULT 1,
    produto_id          varchar(25)   NOT NULL,
    descricao_produto   varchar(255)  NULL,
    data_entrada        date          NULL,
    qtde_recebida       numeric(14,3) NULL,
    filial_id           int           NULL,
    custo_unitario      numeric(12,4) NOT NULL DEFAULT 0,

    CONSTRAINT entradas_mercadoria_pkey
        PRIMARY KEY (ordem_compra, item, produto_id, nro_nfe),

    CONSTRAINT entradas_qtde_ck   CHECK (qtde_recebida IS NULL OR qtde_recebida >= 0),
    CONSTRAINT entradas_custo_ck  CHECK (custo_unitario >= 0)
);

-- NAO existe FK de entradas_mercadoria para pedido_compra.
-- Motivo tecnico: ordem_compra nao e unica em pedido_compra (a PK de la e
-- pedido_id + produto_id + item), entao nao ha chave candidata para referenciar.
-- Motivo de dado: 11 pedidos tem ordem_compra = 0 e nenhuma entrada aponta
-- para eles. Criar a FK exigiria antes uma decisao do cliente sobre esses
-- registros. Item levado para a reuniao de validacao (docs/03).
COMMENT ON TABLE public.entradas_mercadoria IS
    'Entradas de NF. Liga-se a pedido_compra por ordem_compra. FK nao declarada: ordem_compra nao e chave candidata em pedido_compra.';

CREATE INDEX ix_entradas_ordem   ON public.entradas_mercadoria (ordem_compra);
CREATE INDEX ix_entradas_produto ON public.entradas_mercadoria (produto_id);
CREATE INDEX ix_entradas_data    ON public.entradas_mercadoria (data_entrada);


-- =============================================================================
-- 5. VENDA
-- =============================================================================
CREATE TABLE public.venda (
    venda_id        bigint        NOT NULL,
    data_emissao    date          NOT NULL,

    -- [CORRECAO M-01] varchar(8) -> time. Garante valor valido e permite
    -- ordenacao e aritmetica temporal corretas.
    horariomov      time          NOT NULL DEFAULT '00:00:00',

    produto_id      varchar(25)   NOT NULL,

    -- [CORRECAO M-03/M-04] float8 NULL -> numeric NOT NULL.
    qtde_vendida    numeric(14,3) NOT NULL,

    valor_unitario  numeric(12,4) NOT NULL DEFAULT 0,

    -- [CORRECAO M-05] int8 -> int, alinhado com as demais tabelas.
    filial_id       int           NOT NULL DEFAULT 1,

    item            int           NOT NULL DEFAULT 1,
    unidade_medida  varchar(3)    NULL,

    -- [CORRECAO M-06] Constraint renomeada de "pk_consumo" para o nome da tabela.
    CONSTRAINT venda_pkey
        PRIMARY KEY (filial_id, venda_id, data_emissao, produto_id, item, horariomov),

    CONSTRAINT venda_qtde_ck   CHECK (qtde_vendida   >= 0),
    CONSTRAINT venda_valor_ck  CHECK (valor_unitario >= 0)
);

-- A PK de 6 colunas foi mantida por fidelidade ao modelo do cliente, mas e
-- fragil: nao impede o mesmo documento fiscal de entrar duas vezes com
-- horarios diferentes. Recomendacao de evolucao registrada em docs/03.

-- A FK de venda para produtos_filial NAO e criada aqui.
-- Motivo de dado: 13 vendas referenciam produtos P21..P28, inexistentes no
-- cadastro, e 4 vendas referenciam as filiais 2 e 3, tambem sem cadastro.
--
-- A solucao adotada e uma FK NOT VALID, que dispensa a verificacao do
-- historico ja gravado mas passa a valer para todo dado NOVO. Detalhe que
-- costuma passar batido: NOT VALID nao desliga a checagem de INSERT - so
-- pula a varredura das linhas preexistentes. Por isso a constraint precisa
-- ser criada DEPOIS da carga, e nao aqui.
-- Ver o bloco final de sql/02_staging_e_carga.sql.

CREATE INDEX ix_venda_data     ON public.venda (data_emissao);
CREATE INDEX ix_venda_produto  ON public.venda (produto_id);
CREATE INDEX ix_venda_periodo  ON public.venda (data_emissao, produto_id);
